# Generated by Django 3.1.1 on 2020-10-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201005_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='search',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
